[versions]
# SDK versions
compileSdk = "35"
minSdk = "21"
targetSdk = "35"

# Plugins
agp = "8.13.1"
mavenPublish = "0.30.0"

# AndroidX
annotation = "1.9.1"
appcompat = "1.7.0"
testCore = "1.6.1"

# Libraries
material = "1.12.0"
timber = "5.0.1"

# Testing
junit = "4.13.2"
robolectric = "4.14.1"

# Tools
jacoco = "0.8.12"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
test-core = { module = "androidx.test:core", version.ref = "testCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
